/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini.linkedlisttest;

import org.junit.Test;
import static org.junit.Assert.*;

public class TestCase {
	@Test
	public void testSomeLibraryMethod() {

	}
}
